name: Jar Signing

on:
  workflow_dispatch:

jobs:

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-jar-signing-${{ hashFiles('maven/jar-signing/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-jar-signing-
    - name: Create signing JKS
      run: |
        echo "${{ secrets.JSIGN_JKS_FILE_B64 }}" | base64 -d > maven/jar-signing/mykeystore.jks
    - name: Build with Maven
      run: |
        cd maven/jar-signing
        mvn -B package -DjsignAlias=${{ secrets.JSIGN_JKS_ALIAS }} -DjsignStorepass=${{ secrets.JSIGN_JKS_PASS }}

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-jar-signing-${{ hashFiles('maven/jar-signing/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-jar-signing-
    - name: Create signing JKS
      shell: bash
      run: |
        echo "${{ secrets.JSIGN_JKS_FILE_B64 }}" | base64 -d > maven\jar-signing\mykeystore.jks
    - name: Build with Maven
      run: |
        cd maven\jar-signing
        mvn -B package -DjsignAlias=${{ secrets.JSIGN_JKS_ALIAS }} -DjsignStorepass=${{ secrets.JSIGN_JKS_PASS }}
