name: Jar Signing

on:
  workflow_dispatch:

jobs:

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Maven
      run: |
        cd maven/jar-signing
        mvn -B package -DjsignAlias=${{ secrets.JSIGN_JKS_ALIAS }} -DjsignStorepass=${{ secrets.JSIGN_JKS_PASS }}

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Maven
      run: |
        cd maven\jar-signing
        mvn -B package -DjsignAlias=${{ secrets.JSIGN_JKS_ALIAS }} -DjsignStorepass=${{ secrets.JSIGN_JKS_PASS }}
